#!/bin/sh

SESSIONNAME="NAME"
DIRECTORY="~"

if [ "$#" == 1 ]
then
    SESSIONNAME="$SESSIONNAME$1"
fi

if { [ "$TERM" = "screen-256color" ] && [ -n "$TMUX" ]; } then
    tmux send-keys -t $SESSIONNAME "cd " $DIRECTORY C-m
    exit 0
fi

tmux has-session -t $SESSIONNAME

if [ $? != 0 ] then
    tmux new-session -s $SESSIONNAME -n $SESSIONNAME -d
    tmux send-keys -t $SESSIONNAME "cd " $DIRECTORY C-m
fi

tmux attach -t $SESSIONNAME
